[package]
name = "transactions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "transactions"
path = "src/lib.rs"

[[bin]]
name = "loader"
path = "src/main.rs"

[dependencies]
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.87"
anyhow = "1.0.66"
thiserror = "1.0.37"